=== nioomeee/Sem-3-Assignments/XML/assignment 2/4.dtd
<!ELEMENT StudentInfo (Name, personalInfo, Result)>

<!ELEMENT Name (#PCDATA)>
<!ELEMENT personalInfo (address, birthdate, gender, mobile)>

<!ELEMENT address (#PCDATA)>
<!ELEMENT birthdate (#PCDATA)>
<!ELEMENT gender (male | female)>
<!ELEMENT male EMPTY>
<!ELEMENT female EMPTY>
<!ELEMENT mobile (#PCDATA)>

<!ELEMENT Result (total, percentage, grade)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT percentage (#PCDATA)>
<!ELEMENT grade (Pass | First | Dist | Second | Fail)>
<!ELEMENT Pass EMPTY>
<!ELEMENT First EMPTY>
<!ELEMENT Dist EMPTY>
<!ELEMENT Second EMPTY>
<!ELEMENT Fail EMPTY>

=== nioomeee/Sem-3-Assignments/XML/assignment 2/4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Create XML document for Student where it contains the following
data:
Student Name, Personal Info (Address, Birthdate,Gender, Mobile
No, Address) ,Result(Total, Percentage, Grade)
Create External DTD declaration for Student where
• Gender has only two choices Male and Female as an element.
• Grade element should have only one of these grade element
(Pass, First, Dist., Second, Fail) -->
<!DOCTYPE StudentInfo SYSTEM "4.dtd">
<StudentInfo>
    <Name>Donald</Name>
    <personalInfo>
        <address>Disneyland</address>
        <birthdate>03/04/1996</birthdate>
        <gender><male/></gender>
        <mobile>1112223334</mobile>
    </personalInfo>

    <Result>
        <total>600</total>
        <percentage>80%</percentage>
        <grade><Second/></grade>
    </Result>
</StudentInfo>
