=== nioomeee/Sem-3-Assignments/XML/assignment 2/6.dtd
<!ELEMENT StudentInfo (Student)>
<!ELEMENT Student (Name, Id, Plan)>
<!ELEMENT Name (Fname, Lname)>
<!ELEMENT Fname (#PCDATA)>
<!ELEMENT Lname (#PCDATA)>
<!ELEMENT Id (#PCDATA)>
<!ELEMENT Plan (courses)>
<!ELEMENT courses (course*)>
<!ATTLIST courses year NMTOKEN #REQUIRED>
<!ELEMENT course (cName, shortName, record*)>
<!ELEMENT cName (#PCDATA)>
<!ELEMENT shortName (#PCDATA)>
<!ELEMENT record (Grade, Date)>
<!ELEMENT Grade (#PCDATA)>
<!ELEMENT Date (#PCDATA)>

=== nioomeee/Sem-3-Assignments/XML/assignment 2/6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Create an XML document Student where it contains the following data
:
Student(Name (fname & Lname) , ID , Plan (courses) ). In
courses element take (year) as an attribute and (course) as an
sub-element . And Course has name , shortName , record as its
sub element. And again record has its sub element Grade , date.
Create An External DTD for the above XML document where :
• Courses element can zero or more course.
• Year attribute must appear in the element.
• Record element should appear zero or more times. -->
<!DOCTYPE StudentInfo SYSTEM "6.dtd">
<StudentInfo>
    <Student>
        <Name>
            <Fname>Mickey</Fname>
            <Lname>Mouse</Lname>
        </Name>
        <Id>001</Id>
        <Plan>
            <courses year="2">
                <course>
                    <cName>Introduction to Programming</cName>
                    <shortName>ITP</shortName>
                    <record>
                        <Grade>A</Grade>
                        <Date>2023-12-15</Date>
                    </record>
                    <record>
                        <Grade>B</Grade>
                        <Date>2024-01-20</Date>
                    </record>
                </course>
            </courses>
        </Plan>
    </Student>
</StudentInfo>
