=== nioomeee/Sem-3-Assignments/XML/assignment2/10.dtd
<!ELEMENT Student_info (Student+, Course+)>
<!ELEMENT Student (Name, contact_no)>
<!ATTLIST Student which_course ID #REQUIRED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT contact_no (#PCDATA)>
<!ATTLIST contact_no contact NMTOKEN #REQUIRED>
<!ELEMENT Course (cName, Subject)>
<!ATTLIST Course c_id IDREF #REQUIRED>
<!ELEMENT cName (#PCDATA)>
<!ELEMENT Subject EMPTY>
<!ATTLIST Subject name CDATA #REQUIRED>

=== nioomeee/Sem-3-Assignments/XML/assignment2/10.xml
<?xml version="1.0"?>
<!-- Create an XML document Student_info where it contains the following
data :
Student((which_course as attribute), name, contact_no),
Course((c_id as attribute), name), subject(name as attribute)
Create An External DTD for the above XML document where
• student can be one or more times
• c_id as id and which_course as referance id.
• Make one entity of your choice and use in document.
• Make enumerated attributes of subject name as Java, xml, OS
• Make contact_no as nmtoken -->
<!DOCTYPE Student_info SYSTEM "10.dtd">
<Student_info>
    <Student which_course="c_56">
        <Name>Komolika</Name>
        <contact_no contact="99999999"></contact_no>
    </Student>

    <Student which_course="c_20">
        <Name>Prerna</Name>
        <contact_no contact="9198889999"></contact_no>
    </Student>

    <Course c_id="c_20">
        <cName>iMScIT</cName>
        <Subject name="XML"></Subject>
    </Course>

    <Course c_id="c_56">
        <cName>BBA</cName>
        <Subject name="Psychology"></Subject>
    </Course>
</Student_info>
