=== nioomeee/Sem-3-Assignments/XML/assignment2/11.dtd
<!ELEMENT Student (Name, PersonalInfo, Result?)>
    <!ELEMENT Name (#PCDATA)>

<!ENTITY % PersonalInfo "INCLUDE">

<![ %PersonalInfo; [
    <!ELEMENT PersonalInfo (Address, Birthdate, Gender, Mobile)>
        <!ELEMENT Address (#PCDATA)>
        <!ELEMENT Birthdate (#PCDATA)>
        <!ELEMENT Gender (Male | Female)>
            <!ELEMENT Male EMPTY>
            <!ELEMENT Female EMPTY>
        <!ELEMENT Mobile (#PCDATA)>
]]>

<!ENTITY % Result "IGNORE">

<![ %Result; [
    <!ELEMENT Total (#PCDATA)>
    <!ELEMENT Percentage (#PCDATA)>
    <!ELEMENT Grade (Pass | Fail | First | Second | Dist)>
    <!ELEMENT Pass EMPTY>
    <!ELEMENT Fail EMPTY>
    <!ELEMENT First EMPTY>
    <!ELEMENT Second EMPTY>
    <!ELEMENT Dist EMPTY>
]]>

=== nioomeee/Sem-3-Assignments/XML/assignment2/11.xml
<?xml version="1.0"?>
<!-- Create XML document for Student where it contains the following
data:
Student Name, Personal Info (Address, Birthdate,Gender, Mobile
No, Address) ,Result(Total, Percentage, Grade)
Create External DTD declaration for Student where
• Gender has only two choices Male and Female as an element.
• Grade element should have only one of these grade element
(Pass, First, Dist., Second, Fail)
Use conditional statement INCLUDE of student
personal information DTD and IGNORE of result DTD) -->
<!DOCTYPE Student SYSTEM "11.dtd">
<Student>
    <Name>Krishna</Name>
    <PersonalInfo>
        <Address>Gokul ki gali</Address>
        <Birthdate>Janmashtmi</Birthdate>
        <Gender>
            <Male/>
        </Gender>
        <Mobile>999-RADHA</Mobile>
    </PersonalInfo>
    <!-- <Result>
        <Total>350</Total>
        <Percentage>70%</Percentage>
        <Grade>
            <Pass></Pass>
        </Grade>
    </Result> -->
</Student>
