=== nioomeee/Sem-3-Assignments/XML/assignment2/4.dtd
<!ELEMENT Student (Name, PersonalInfo, Result)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT PersonalInfo (Address, Birthdate, Gender, MobileNo)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Birthdate (#PCDATA)>
<!ELEMENT Gender (Male | Female)>
<!ELEMENT Male (#PCDATA)>
<!ELEMENT Female (#PCDATA)>
<!ELEMENT MobileNo (#PCDATA)>
<!ELEMENT Result (Total, Percentage, Grade)>
<!ELEMENT Total (#PCDATA)>
<!ELEMENT Percentage (#PCDATA)>
<!ELEMENT Grade (Pass | First | Dist | Second | Fail)>
<!ELEMENT Pass (#PCDATA)>
<!ELEMENT First (#PCDATA)>
<!ELEMENT Dist (#PCDATA)>
<!ELEMENT Second (#PCDATA)>
<!ELEMENT Fail (#PCDATA)>

=== nioomeee/Sem-3-Assignments/XML/assignment2/4.xml
<?xml version="1.0" standalone="no"?>
<!-- Create XML document for Student where it contains the following
data:
Student Name, Personal Info (Address, Birthdate,Gender, Mobile
No, Address) ,Result(Total, Percentage, Grade)
Create External DTD declaration for Student where
• Gender has only two choices Male and Female as an element.
• Grade element should have only one of these grade element
(Pass, First, Dist., Second, Fail) -->

<!DOCTYPE Student SYSTEM "4.dtd">

<Student>
    <Name>Nobita</Name>
    <PersonalInfo>
        <Address>321, Kasukabe, Japan</Address>
        <Birthdate>May 5, 1990</Birthdate>
        <Gender>
            <Male></Male>
        </Gender>
        <MobileNo>555-SHINCHAN</MobileNo>
    </PersonalInfo>
    <Result>
        <Total>350</Total>
        <Percentage>70%</Percentage>
        <Grade>
            <Pass></Pass>
        </Grade>
    </Result>
</Student>
