=== nioomeee/Sem-3-Assignments/XML/assignment2/8.dtd
<!ELEMENT Student (Roll_no, Name, Marks, Rank)>
<!ELEMENT Roll_no (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Marks (WebTechnologies, XML, J2EE, NS)>
<!ELEMENT WebTechnologies (#PCDATA)>
<!ELEMENT XML (#PCDATA)>
<!ELEMENT J2EE (#PCDATA)>
<!ELEMENT NS (#PCDATA)>
<!ELEMENT Rank (#PCDATA)>

=== nioomeee/Sem-3-Assignments/XML/assignment2/8.xml
<?xml version="1.0" standalone="no"?>
<!-- Create an XML document Student where it contains the following
    data :
     Student (Roll_no , Name , Marks , Rank)
    Create An External DTD for the above XML document where
    â€¢ Marks element has web technologies , XML , J2EE ,NS as a subelement
    â€¢ Marks can have only the above elements. -->
<!DOCTYPE Student SYSTEM "8.dtd">

<Student>
    <Roll_no>21</Roll_no>
    <Name>Krishna</Name>
    <Marks>
        <WebTechnologies>89</WebTechnologies>
        <XML>87</XML>
        <J2EE>78</J2EE>
        <NS>84</NS>
    </Marks>
    <Rank>5</Rank>
</Student>
