=== nioomeee/Sem-3-Assignments/XML/assignment2/9.dtd
<!ELEMENT Letter (Contact, Salutation, Paragraph, Closing, Signature)>
<!ELEMENT Contact (Name, Address, City, Pin, State, Flag)>
<!ATTLIST Contact type CDATA #FIXED "sender">
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT Pin (#PCDATA)>
<!ELEMENT State (#PCDATA)>
<!ELEMENT Flag EMPTY>
<!ATTLIST Flag gender (male | female) "male">
<!ELEMENT Salutation (#PCDATA)>
<!ELEMENT Paragraph (#PCDATA)>
<!ELEMENT Closing (#PCDATA)>
<!ELEMENT Signature (#PCDATA)>

=== nioomeee/Sem-3-Assignments/XML/assignment 2/9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Create an XML document Letter where it contains the following data :
Letter (contact (name , address , city ,pin ,state , flag) , salutation
, paragraph , closing , signature ) . The “contact “ element has an
attribute “type” where it will declare type of person (eg :
manager , officer etc as a value) .
Create An External DTD for the above XML document where
• contact should come atleast once.
• flag element should an empty element
• “flag” element has an attribute “gender” where it will declare as
a male or female as a value and male as a default value.
• The attribute type has a fixed value “sender” -->
<!DOCTYPE Letter SYSTEM "9.dtd">
<Letter>
    <Contact type="sender">
        <Name>Donald</Name>
        <Address>Disneyland</Address>
        <City>Hong Kong</City>
        <Pin>56003</Pin>
        <State>China</State>
        <Flag gender="Male" />
    </Contact>

    <Salutation>Dear Sir,</Salutation>

    <Paragraph>This is a formal letter to inform you about the recent changes in our company policy.</Paragraph>

    <Closing>Sincerely,</Closing>

    <Signature>Donald Duck</Signature>
</Letter>

=== nioomeee/Sem-3-Assignments/XML/assignment2/9.xml
<?xml version="1.0" standalone="no"?>
<!-- Create an XML document Letter where it contains the following data :
Letter (contact (name , address , city ,pin ,state , flag) , salutation
, paragraph , closing , signature ) . The “contact “ element has an
attribute “type” where it will declare type of person (eg :
manager , officer etc as a value) .
Create An External DTD for the above XML document where
• contact should come atleast once.
• flag element should an empty element
• “flag” element has an attribute “gender” where it will declare as
a male or female as a value and male as a default value.
• The attribute type has a fixed value “sender” -->
<!DOCTYPE Letter SYSTEM "9.dtd">

<Letter>
    <Contact type="sender">
        <Name>John Cena</Name>
        <Address>123 NewStreet, USA</Address>
        <City>Venice</City>
        <Pin>380001</Pin>
        <State>California</State>
        <Flag gender="male"></Flag>
    </Contact>

    <Salutation>Dear, Mr. Cena</Salutation>
    <Paragraph>Hello, When are you thinking about showing up?</Paragraph>
    <Closing>Sincerely,</Closing>
    <Signature>Anant Ambani</Signature>
</Letter>
